### ISSUE TITLE
Error: Cannot find module 'xmlbuilder'

### ISSUE THREAD

**Issue by tjohnman** [hmerritt/android-sdk#1]
I followed the instructions and then tried running `npx eas-cli build --local -p android --profile production` to run my project, but I was met with `Error: Cannot find module 'xmlbuilder'`.

I fixed it by installing eas-cli inside the container like so: `npm i -g eas-cli`. In case anyone encounters this same error.

**Comment by hmerritt** [comment]
Thank you for bringing this issue to light 👍

It's a little strange that installing `eas-cli` fixed it - this should have been installed automatically in the docker build.

I'll have a little poke around.

**Comment by hmerritt** [comment]
So it looks like you need to call `eas` (instead of `eas-cli`)

![image](https://github.com/hmerritt/android-sdk/assets/17837575/3eb186ca-6e11-4843-a854-cd8c056ba259)

Hopefully that wraps this issue up (if not, feel free to create another, or comment below here)
